name: API Cron Job

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (GitHub Actions minimum)
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
    - name: Call API
      run: curl -s -o /dev/null -w "%{http_code}" http://f1124820.xsph.ru/index.php
